### ISSUE TITLE
Can't define methods

### ISSUE THREAD

**Issue by willfaught** [x-motemen/gore#34]
```
$ gore
gore version 0.2.2  :help for help
gore> type X struct {}
gore> func (X) Y() {}
..... 
..... 
..... 
```

**Comment by motemen** [comment]
Thanks, currently gore does not support top-level definitions as it injects code inside `main()`. Marked as a feature request and I'm gonna try it later.

**Comment by willfaught** [comment]
OK, thanks. Even a message saying it's not supported would be fine; it seems like I hit a bug otherwise.

**Comment by motemen** [comment]
Ah, agreed. Current behavior must be confusing.

**Comment by Lenskiy** [comment]
Would it be possible to search for the keyword **func** and if it is, copy whatever follows, to right before the main func ?

**Comment by itchyny** [comment]
The issue is resolved now.

**Comment by xiantang** [comment]
![image](https://user-images.githubusercontent.com/34479567/145667418-c19c901c-7192-4341-a23b-a43ba3db0447.png)
still not support struct method in 0.5.3

**Comment by itchyny** [comment]
Reopening as the original issue is not still resolved in 0.5.3.

**Comment by itchyny** [comment]
This has been resolved in v0.5.5.

**Comment by willfaught** [comment]
@motemen @itchyny Thank you! 🙏
